language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  
script:
  - python -m pytest
  
after_success:
  - coveralls
